server {
    listen       80;
    server_name  localhost;

    resolver 223.5.5.5 119.29.29.29 ipv6=off valid=300s;

    location ~ ^/upgrade/api/(v[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?)$ {
        add_header Cache-Control "no-cache";
        proxy_ssl_server_name on;
        proxy_set_header Host cdn.w7.cc;
        proxy_intercept_errors on;
        error_page 404 500 502 503 504 = @empty_upgrade;
        proxy_pass https://cdn.w7.cc/dpanel/upgrade/$1.md$is_args$args;
    }

    location = /upgrade/api/release {
        add_header Cache-Control "no-cache";
        proxy_ssl_server_name on;
        proxy_set_header Host cdn.w7.cc;
        proxy_pass https://cdn.w7.cc/dpanel/upgrade/release.md$is_args$args;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ $uri.html =404;
    }

    location @empty_upgrade {
        return 204;
    }

    error_page   500 502 503 504  /50x.html;

    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
