server {
    listen 80;
    server_name dpanel.cc www.dpanel.cc;

    location = /upgrade/api/latest {
        add_header Cache-Control "no-cache";
        proxy_ssl_server_name on;
        proxy_set_header Host cdn.w7.cc;
        proxy_pass https://cdn.w7.cc/dpanel/upgrade/latest.md;
    }

    location = /upgrade/api/release {
        add_header Cache-Control "no-cache";
        proxy_ssl_server_name on;
        proxy_set_header Host cdn.w7.cc;
        proxy_pass https://cdn.w7.cc/dpanel/upgrade/release.md;
    }
}
